# .readthedocs.yaml
# Read the Docs configuration file
version: 1

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub

python:
  install:
    - requirements: docs/requirements.txt

